-- SQL DDL script
-- Generated file - do not edit

create table `ISSUE_COMMENT` (`USER_NAME` VARCHAR(254) NOT NULL,`REPOSITORY_NAME` VARCHAR(254) NOT NULL,`ISSUE_ID` INTEGER NOT NULL,`COMMENT_ID` INTEGER AUTO_INCREMENT PRIMARY KEY,`ACTION` VARCHAR(254),`COMMENTED_USER_NAME` VARCHAR(254) NOT NULL,`CONTENT` VARCHAR(254),`REGISTERED_DATE` DATE NOT NULL,`UPDATED_DATE` DATE NOT NULL)

create table `ACTIVITY` (`ACTIVITY_ID` INTEGER AUTO_INCREMENT PRIMARY KEY,`USER_NAME` VARCHAR(254) NOT NULL,`REPOSITORY_NAME` VARCHAR(254) NOT NULL,`ACTIVITY_USER_NAME` VARCHAR(254) NOT NULL,`ACTIVITY_TYPE` VARCHAR(254) NOT NULL,`MESSAGE` VARCHAR(254) NOT NULL,`ADDITIONAL_INFO` VARCHAR(254) NOT NULL,`ACTIVITY_DATE` DATE NOT NULL)

create table `ISSUE_LABEL` (`USER_NAME` VARCHAR(254) NOT NULL,`REPOSITORY_NAME` VARCHAR(254) NOT NULL,`ISSUE_ID` INTEGER NOT NULL,`LABEL_ID` INTEGER NOT NULL)

create table `LABEL` (`USER_NAME` VARCHAR(254) NOT NULL,`REPOSITORY_NAME` VARCHAR(254) NOT NULL,`LABEL_ID` INTEGER AUTO_INCREMENT PRIMARY KEY,`LABEL_NAME` VARCHAR(254) NOT NULL,`COLOR` VARCHAR(254) NOT NULL)

create table `REPOSITORY` (`USER_NAME` VARCHAR(254) NOT NULL,`REPOSITORY_NAME` VARCHAR(254) NOT NULL,`PRIVATE` BOOLEAN NOT NULL,`DESCRIPTION` VARCHAR(254) NOT NULL,`DEFAULT_BRANCH` VARCHAR(254) NOT NULL,`REGISTERED_DATE` DATE NOT NULL,`UPDATED_DATE` DATE NOT NULL,`LAST_ACTIVITY_DATE` DATE NOT NULL,`ORIGIN_USER_NAME` VARCHAR(254) NOT NULL,`ORIGIN_REPOSITORY_NAME` VARCHAR(254) NOT NULL,`PARENT_USER_NAME` VARCHAR(254) NOT NULL,`PARENT_REPOSITORY_NAME` VARCHAR(254) NOT NULL)

create table `ISSUE` (`USER_NAME` VARCHAR(254) NOT NULL,`REPOSITORY_NAME` VARCHAR(254) NOT NULL,`ISSUE_ID` INTEGER AUTO_INCREMENT PRIMARY KEY,`OPENED_USER_NAME` VARCHAR(254) NOT NULL,`MILESTONE_ID` INTEGER NOT NULL,`ASSIGNED_USER_NAME` VARCHAR(254) NOT NULL,`TITLE` VARCHAR(254) NOT NULL,`CONTENT` VARCHAR(254) NOT NULL,`CLOSED` BOOLEAN NOT NULL,`REGISTERED_DATE` DATE NOT NULL,`UPDATED_DATE` DATE NOT NULL,`PULL_REQUEST` BOOLEAN NOT NULL)

create table `COMMIT_LOG` (`USER_NAME` VARCHAR(254) NOT NULL,`REPOSITORY_NAME` VARCHAR(254) NOT NULL,`COMMIT_ID` VARCHAR(254) NOT NULL)

create table `User` (`USER_NAME` VARCHAR(254) NOT NULL PRIMARY KEY,`FULL_NAME` VARCHAR(254) NOT NULL,`MAIL_ADDRESS` VARCHAR(254) NOT NULL,`PASSWORD` VARCHAR(254) NOT NULL,`ADMINISTRATOR` BOOLEAN NOT NULL,`URL` VARCHAR(254) NOT NULL,`REGISTERED_DATE` DATE NOT NULL,`UPDATED_DATE` DATE NOT NULL,`LAST_LOGIN_DATE` DATE NOT NULL,`IMAGE` VARCHAR(254) NOT NULL,`GROUP_ACCOUNT` BOOLEAN NOT NULL,`REMOVED` BOOLEAN NOT NULL)